name: Deploy React to AWS
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react-3
          environment_name: Docker-react-3-env
          version_label: "Label6"
          version_description: "Deployed from GitHub actions"
          existing_bucket_name: lucky-quit-bucket
          region: us-west-1
          deployment_package: deploy.zip